OUT=task_01 task_02 task_03 task_04 task_05 task_06 task_07

all: $(OUT)

task_01: task_01.cpp
	g++ -o task_01 task_01.cpp

task_02: task_02.cpp
	g++ -o task_02 task_02.cpp

task_03: task_03.cpp
	g++ -o task_03 task_03.cpp

task_04: task_04.cpp
	g++ -o task_04 task_04.cpp

task_05: task_05.cpp
	g++ -o task_05 task_05.cpp

task_06: task_06.cpp
	g++ -o task_06 task_06.cpp

task_07: task_07.cpp
	g++ -o task_07 task_07.cpp

clean:
	rm -rf $(OUT)
